import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import "./globals.css";
import { NextProviders } from "./NextProviders";

const instrument = Instrument_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Devlinks",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${instrument.className} bg-white sm:bg-lightGrey min-h-dvh`}
			>
				<NextProviders>{children}</NextProviders>
			</body>
		</html>
	);
}
